services:
  - type: web
    name: condominio-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: MONGODB
        value: mongodb://localhost/condominio-app
      - key: JWT_SECRET
        value: dsfafahj332q424fdss
      - key: JWT_REFRESH_SECRET
        value: 436543534efdsfdsa
      - key: JWT_EXPIRES_IN
        value: 2h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: IS_EMAIL_VERIFICATION_ENABLED
        value: false
      - key: EMAIL_VERIFICATION_SECRET
        value: fdasfadsfgcfhd54676543
      - key: EMAIL_VERIFICATION_EXPIRES_IN
        value: 24h
      - key: EMAIL_VERIFICATION_URL
        value: http://localhost:3000/api/v1/auth/verify-email
      - key: EMAIL_VERIFICATION_SUBJECT
        value: Verificion de e-mail
      - key: EMAIL_VERIFICATION_SENDER
        value: info@trial-69oxl5e27jzl785k.mlsender.net
      - key: EMAIL_VERIFICATION_TEST_ENABLED
        value: true
      - key: EMAIL_VERIFICATION_TEST_NAME
        value: Test
      - key: EMAIL_VERIFICATION_TEST_EMAIL
        value: jethro.gutierrez@gmail.com
      - key: RESET_PASSWORD_SECRET
        value: fdasfadsfgcfhd54676543
      - key: RESET_PASSWORD_URL
        value: http://localhost:3000/api/v1/auth/reset-password
      - key: BCRYPT_SALT
        value: 10
      - key: PORT
        value: 3000
      - key: MAILERSEND_API_KEY
        value: mlsn.eb5d74d6f38f72eb12f9d1ecd2c0d6b06ead10afe1f5c24449d1456c729be659
      - key: HOST_FRONT
        value: http://localhost:4200