
@email=jethro.gutierrez@gmail.com
@password=Password123
@name=Jethro gutierrez

@host=http://localhost:3000

### Iniciar sesión
# @name loginUser
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

@accessToken= {{loginUser.response.body.$.accessToken}}

### Obtener todos los condominios
# @name getAllCondominiums
GET {{host}}/api/v1/condominiums?page=1&limit=10
Authorization: Bearer {{accessToken}}
Accept: application/json

@condominiumId={{getAllCondominiums.response.body.$.data[0]._id}}


### Obtener todos los apartamentos
# @name getAllApartments
GET {{host}}/api/v1/condominiums/{{condominiumId}}/apartments?page=1&limit=10
Authorization: Bearer {{accessToken}}
Accept: application/json

@apartmentId={{getAllApartments.response.body.$.data[0]._id}}



### Obtener todas las cuotas de mantenimiento
# @name getAllMaintenanceFees
GET {{host}}/api/v1/condominiums/{{condominiumId}}/maintenance-fees?page=1&limit=10
Authorization: Bearer {{accessToken}}
Accept: application/json


@maintenanceFeeId={{getAllMaintenanceFees.response.body.$.data[0]._id}}
### Obtener todas las cuotas de mantenimiento



### Crear un pago
# @name createPayment
POST {{host}}/api/v1/condominiums/{{condominiumId}}/apartments/{{apartmentId}}/payments/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "idempotencyKey": "unique-key-12345",
  "amount": 1500,
  "paymentDate": "2025-05-15",
  "paymentMethod": "TRANSFERENCIA",  
  "transactionId":"xxxxx",
  "paymentReference":"xxxxx",
  "maintenanceFeeId":"{{maintenanceFeeId}}",
    
    "status": "ACTIVE",
    "currency": "MX",
   
    "paymentStatus": "PENDING"
 
   
  
}

##########

## Obtener todos los pagos de una cuota de mantenimiento
# @name getAllPayments
GET {{host}}/api/v1/condominiums/{{condominiumId}}/apartments/{{apartmentId}}/payments?page=1&limit=10
Authorization: Bearer {{accessToken}}
Accept: application/json

@paymentId={{getAllPayments.response.body.$.data[0]._id}}


### Obtener un pago por ID
# @name getPaymentById
GET {{host}}/api/v1/condominiums/{{condominiumId}}/apartments/{{apartmentId}}/payments/681267938b4a65237ebcee69
Authorization: Bearer {{accessToken}}
Accept: application/json


### Actualizar un pago
# @name updatePayment
PATCH {{host}}/api/v1/condominiums/{{condominiumId}}/apartments/{{apartmentId}}/payments/{{paymentId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "amount": 1500,
  "paymentDate": "2025-05-15",
  "paymentMethod": "TRANSFERENCIA",  
  "transactionId":"xxxxx",
  "paymentReference":"xxxxx",
    "maintenanceFeeId":"{{maintenanceFeeId}}",
    "paymentMethodId":"",
    "status": "ACTIVE",
    "currency": "MX",
    "paymentType": "CASH",
    "paymentStatus": "PENDING"
}


### Eliminar un pago
# @name deletePayment
DELETE {{host}}/api/v1/condominiums/{{condominiumId}}/apartments/{{apartmentId}}/payments/{{paymentId}}
Authorization: Bearer {{accessToken}}