
export enum CommonServiceStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    SUSPENDED = 'SUSPENDED',
    DELETED = 'DELETED',
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    IN_PROGRESS = 'IN_PROGRESS',
    FAILED = 'FAILED',
    SUCCESS = 'SUCCESS',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    PENDING_PAYMENT = 'PENDING_PAYMENT',
    PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
    PENDING_VERIFICATION = 'PENDING_VERIFICATION',
    PENDING_REVIEW = 'PENDING_REVIEW'
}